[context]
title = "Welcome to QACZAR!"
description = "QACZAR is a thing!"

[links]
twitter = "https://twitter.com/arthexis"
github = "https://github.com/arthexis/qaczar"
facebook = "https://www.facebook.com/arthexis"
